### ISSUE TITLE
ValueError on uic.loadUi with custom widgets which set different sip API version.

### ISSUE THREAD

**Issue by jono1515** [MaurizioB/nolae#1]
Hi @MaurizioB , thanks for providing this tool! I just got a novation launchcontrol xl and run ubuntu 16.04 and have been wanting something just like this. But I'm having some trouble getting it to run properly. 

Here are the errors I'm getting 
jono@galago:~/nolae/NoLaE$ ./launchcontrol.py -M
Traceback (most recent call last):
  File "./launchcontrol.py", line 2780, in <module>
    main()
  File "./launchcontrol.py", line 2773, in main
    win = Win(mode=args.mode, map_file=args.mapfile, config=args.config, backend=args.backend)
  File "./launchcontrol.py", line 62, in __init__
    uic.loadUi('launchcontrol.ui', self)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/__init__.py", line 236, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/Loader/loader.py", line 50, in __init__
    UIParser.__init__(self, QtCore, QtGui, LoaderCreatorPolicy(package))
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/uiparser.py", line 170, in __init__
    self.factory = QObjectCreator(creatorPolicy)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/objcreator.py", line 94, in __init__
    modinfo = plugin_locals["moduleInformation"]()
  File "<string>", line 52, in moduleInformation
  File "/usr/lib/python2.7/dist-packages/qgis/__init__.py", line 26, in <module>
    from qgis.PyQt import QtCore
  File "/usr/lib/python2.7/dist-packages/qgis/PyQt/QtCore.py", line 28, in <module>
    sip.setapi(api, 2)
ValueError: API 'QDate' has already been set to version 1

I'm not sure but it seems like it's looking for a module under a different name than my installation of python has it. Any thoughts?

Thanks again, looking forward to getting this working!

**Comment by MaurizioB** [comment]
Hi there,
I think that it might be a problem related to PyQt4, can you run this command on a terminal and paste here its output?

    $ python -c "from PyQt4.QtCore import QT_VERSION_STR; print QT_VERSION_STR; from PyQt4.Qt import PYQT_VERSION_STR; print PYQT_VERSION_STR"

**Comment by jono1515** [comment]
Thanks @MaurizioB, here's what I get with that command -
`jono@galago:~/$ python -c "from PyQt4.QtCore import QT_VERSION_STR; print QT_VERSION_STR; from PyQt4.Qt import PYQT_VERSION_STR; print PYQT_VERSION_STR"
4.8.7
4.11.4
`

**Comment by MaurizioB** [comment]
Hi Jono, I didn't realize that the error comes from a module named qgis, which should have nothing to do with NoLaE, but is being invoked by PyQt for some reason. Qgis is a geographic information system application, and should not "intrude" like that. Have you installed it by purpose? Or do you use some map/geographic related software?
As far as I understand, it shouldn't come with a default ubuntu installation.
We could try to launch NoLaE in a virtualenv with just pyqt, but I'd prefer not to follow that route.

**Comment by jono1515** [comment]
Thanks Maurizio, I'm a geologist and I do use qgis. I wouldn't want to remove it. However... I did set up a separate partition to run ubuntu studio specifically. I was hoping I could use the kernel that specifically attempts to lower latency times. So I could try using your tool on that environment which would not have qgis present. It sounds like that would work. I can't switch over to that environment right now but I will at some point today and see if it works over there. I'll come back and confirm this later on. Thanks again for your help with this, I'm really looking forward to using the launch controller!

**Comment by MaurizioB** [comment]
That's it :)
For now I'm leaving the bug open, in the meantime I'm contacting people on #qgis channel to ask for some clarification, let me know if it works fine on the other environment when you can!

**Comment by jono1515** [comment]
It's working fine with on the other environment without qgis! Thanks!!

**Comment by MaurizioB** [comment]
@jono1515 Good to know!
I received an answer from the dev team, it looks like uic.loadUi (which is the function that is responsible of loading a graphical interface file, such as a window), automatically loads all "widgets" that are currently available in the system, such as custom buttons, data field and so on; I suppose, then, that qgis installs some custom Qt widgets which, since they use a different API version, create the incompatibility.
I'll make a test in the next days, maybe there's a workaround for this problem; I'd be glad to have a report from you, if that's ok.

**Comment by jono1515** [comment]
That's a great development on this! Unfortunately I won't be able to test anything out for a little while... I spilled a beer on my laptop and seem to have fried the motherboard. I'm waiting for my new laptop to arrive. I'll probably be able to test things out in a week or two. I'll be eager to test things out though as soon as I can!
